# Generated by Django 5.1.1 on 2024-11-15 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_enrollment_course_alter_enrollment_student'),
        ('grades', '0003_initial'),
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student'),
        ),
    ]
